configVersion: 1.5.5

# Auto Update the BattleArena plugin (only works for uniz/linux/mac)
# Updates will be retrieved from the latest plugin on the bukkit site
autoUpdate: true

## What is the money on this server called
moneyName: Gold

### Misc Options
# some servers like to teleport people into the floor, you can adjust the Y offset of the teleport
# to make them teleport higher by default, 1.0 = 1 block
teleportYOffset: 1.0

# When a player joins an arena and their inventory is stored
# how many old inventories should be saved
# put in 0 if you don't want this option
numberSavedInventories: 5

# which player commands should be disabled when they enter an arena
disabledCommands: [home, spawn, payhome, warp, watch, sethome, ma]

# If set to true, items that are usually not stackable will be stacked when
# a player is given items.  Examples: 64 mushroom soup, or 64 snow_ball, instead of 1 or 16
ignoreMaxStackSize: false

## default Options (these can be overridden by each match/event type)
defaultOptions:
    ### Match Options
    secondsTillBegin: 6 
    secondsTillMatch: 6 
    secondsToLoot: 5 ## Time after winning to run around and collect loot
    matchTime: 120 ## How long do timed matches last, (in seconds)
    matchUpdateInterval: 30 ## For timed matched, how long between sending players match updates

    ### Event Options
    eventCountdownTime: 180 ## How long before announcing an automated event and its start
    eventCountdownInterval: 60 ## How often will it announce a reminder that its open and you can join
    ## If true, when a player joins and an event that can be opened, it will be
    ## silently opened and the player will join
    allowPlayerCreation: false

    ### Duel Options
    allowRatedDuels: false
    # after a player rejects a duel, how long before they can be challenged again
    challengeInterval: 1800 # (seconds) 1800 = 30minutes

    ### Scheduled Event Options
    ### Valid options [startContinuous, startNext]
    onServerStart: []
    timeBetweenScheduledEvents: 30 ## seconds between end of one event, and start of another

    ### Match/Event Announcements
    ## these only affect the broadcasts to the server or channel, not the messages the fighting players receive
    ## announce : announce these messages 
    ## dontannounce : dont announce these messages
    ## server : use herochat with the channel specified
    ## herochat=<channel> : use herochat with the channel specified
    announcements:
        onPreStart: [ announce, server ]  ## match going to happen soon, example 'P1[p1Elo] vs P2[p2elo]'
        onStart: [ dontannounce ]  ## match starting
        onVictory:  [ announce, server ] ## match has been won, exmaple 'P1[p1elo] has defeated P2[p2elo]'

    ### Default event Announcements
    eventAnnouncements:
        onCountDownToEvent: [ announce, server ]  ## event is now open
        onOpen: [ announce, server ]  ## event is now open
        onStart: [ announce, server ]  ## event is starting
        onVictory:  [ announce, server ] ## event has been won

### Prerequisites
# prerequisites is what they need to have BEFORE joining, this will also be rechecked when the players teleport in
# if there is money, this is taken from their account when they type the command to join
# Prerequisite Options
# needsArmor
# needsItems: if specified you need an item list below
# money=<amount of money>
# maxElo=<maximum elo to join>
# minElo=<minimum elo to join>

### Match Stages
# onOpen: *only called for events, such as ffa/tourney, that have an open stage.
# onPrestart: happens secondsTillMatch seconds before onStart
# onStart: Start of match
# onVictory : happens when match is won by a player
# onComplete: What happens after the match, happens between the time period (onVictory + timeToLoot)
#             if onComplete contains clearInventory it will not allow a player to take inventory out of the arena
#             (except for prize items, or givenItems from onComplete)

### Match Transition Events
# onSpawn: Happens on teleport or on player Respawn ( if respawn is set within onDeath)
# onDeath: What happens when a player dies
# onJoin: player joining a match
# onEnter: Happens when the player first enters the arena.  right after before they are teleported in.  
# onLeave: Happens when the player leaves the arena(aka if they win(after onComplete), or if they die(and dont respawn) )

### Prizes
# winner: given to the winner after onComplete
# losers: given to the losers after onCompletete
# firstPlace: (for tourneys) given to winner after tournament complete
# participants: (for tourneys) given to all participants(except winner) after tournament complete

# valid options for everything but preReqs
# clearInventory,
# giveItems: needs a list under items
# teleportIn
# teleportOut
# pvpon or pvpoff
# health=<health amount>
# hunger=<hunger amount>
# money=<money to give>
# experience=<exp to give>
# teamPvpOn : if not specified defaults to off
# respawn: 
# enchants: needs a list of enchants under enchants
# deEnchant: get rid of all potion effects on player
# disguiseAll=<name>: disguise all players with the given value
# undisguise: undisguise players
# storeExperience/restoreExperience: store/restore Experience 
# storeItems/restoreItems : store/restore items

## Defaults: these events(if not overwritten) get filled with the following values
# onEnter:
#    options: [storeExperience, storeItems(if preReqs contains clearInventory)] 
# onLeave:
#    options: [restoreExperience, restoreItems(if preReqs contains clearInventory)] 

#### Events vs Matches
### Events
## Events can have "open" phases were people are joining but the event hasnt started
## They also can have multiple "matches" that occur as part of the event (like a tournament, where 
## each match is part of the whole 'Tournament Event')
## Some Events like the FreeForAll only have 1 match, but still have the open phase that lasts until someone starts it
### Match
## a single battle between teams

### Arena
arena:
    enabled: true
    type: arena
    database: arena
    rated: true
    prefix: "&6[Arena]&e"
    nTeams: 2+
    teamSize: 1+
    onJoin:
        options: [pvpOff]
    preReqs:
        options: [clearInventory]
    onStart:
        options: [teleportIn, pvpOn, blockBreakOff, woolTeams]
    onSpawn:
        options: [deEnchant, giveItems, hunger=20, health=20]
        giveClass:
            default: gladiator
        items: # ignored if options doesnt have "giveItems"
            - bread: 5
    onDeath:
        options: [clearInventory]
    onComplete:
        options: [teleportOut, deEnchant, clearInventory]
    winner:
        options: [health=20, hunger=20]


### Skirmish 
skirmish:
    enabled: true
    type: skirmish
    database: arena
    rated: false
    prefix: "&b[Skirmish]&e"
    nTeams: 2+
    teamSize: 1+
    onStart:
        options: [teleportIn, pvpOn, blockBreakOff, woolTeams]
    onComplete:
        options: [teleportOut]
    winner:
        options: [health=20, hunger=20]
 

### BattleGround
battleground:
    enabled: true
    command: bg
    type: battleground
    database: bg
    prefix: "&c[Battleground]&e"
    victoryCondition: highestKills
    matchTime: 60
    nTeams: 4
    teamSize: 1
    preReqs:
        options: [clearInventory]
    onJoin:
        options: [pvpOff]
    onPrestart:
        options: [pvpOff, teleportIn, giveItems, deEnchant]
        giveClass:
            default: gladiator
        items: # ignored if options doesnt have "giveItems"
            - bread: 5
    onStart:
        options: [pvpOn]
    onComplete:
        options: [teleportOut, clearInventory, deEnchant ]
    onSpawn:
        options: [enchants, health=20, hunger=20, deEnchant, woolTeams]
        enchants:
            - speed:3
    onDeath:
        options: [respawn, clearInventory]
    winner:
        options: [enchants, health=20, hunger=20]
        enchants:
            - speed:1:900
            - resistance:1:900
            
### Colliseum
colliseum:
    enabled: true
    command: col
    type: colliseum
    database: col
    nTeams: 4
    teamSize: 1
    preReqs:
        options: [clearInventory]
    onJoin:
        options: [pvpOff]
    onPrestart:
        options: [pvpOff, teleportIn, deEnchant, woolTeams]
    onStart:
        options: [pvpOn]
    onComplete:
        options: [teleportOut, clearInventory, deEnchant, undisguise]
    onSpawn:
        options: [enchants, health=20, hunger=20, deEnchant,giveItems, woolTeams]
        enchants:
            - speed:1
        items: # ignored if options doesnt have "giveItems"
            - diamond_sword: sharpness:1 1
            - bow: 1
            - arrow: 32
            - diamond_helm: 1
            - diamond_chest: 1
            - diamond_leggings: 1
            - diamond_boot: 1
    onDeath:
        options: [respawn, clearInventory]
    winner:
        options: [enchants, money=1,experience=300, health=20, hunger=20]
        enchants:
            - speed:1:900
            - resistance:1:900

#### EVENTS ####
### FFA Event
freeForAll:
    enabled: true
    command: ffa
    type: ffa
    database: ffa
    prefix: "&c[FFA]&e"
    nTeams: 2+
    teamSize: 1+
    announcements: ### Override the match victory announcement as the event has one too
        onVictory:  [ dontannounce ] 
    preReqs:
        options: [clearInventory]
    onJoin:
        options: [teleportIn, woolTeams]
    onOpen:
        options: [pvpOff]
    onPrestart:
        options: [pvpOff, giveItems, deEnchant]
        items: # ignored if options doesnt have "giveItems"
            - iron_sword: 1
            - bow: 1
            - tnt: 3
            - arrow: 32
            - leather_helm: 1
            - leather_chest: 1
            - leather_leggings: 1
            - leather_boot: 1
            - bread: 5
    onStart:
        options: [pvpOn]
    onComplete:
        options: [teleportOut, clearInventory, deEnchant, undisguise]
    onSpawn:
        options: [enchants, health=20, hunger=20, deEnchant]
        enchants:
            - speed:3
    winner:
        options: [enchants, money=1,experience=300, health=20, hunger=20]
        enchants:
            - speed:2:900
            - resistance:2:900

### Death Match Event
deathMatch:
    enabled: true
    command: dm
    type: deathMatch
    victoryCondition: highestKills
    database: dm
    prefix: "&8[DeathMatch]&e"
    nTeams: 2+
    teamSize: 1+
    announcements: ### Override the match victory announcement as the event has one too
        onVictory:  [ dontannounce ] 
    preReqs:
        options: [clearInventory]
    onJoin:
        options: [teleportIn, woolTeams]
    onOpen:
        options: [pvpOff]
    onStart:
        options: [pvpOn]
    onComplete:
        options: [teleportOut, clearInventory, deEnchant, undisguise]
    onSpawn:
        options: [enchants, giveItems, health=20, hunger=20, deEnchant]
        items: # ignored if options doesnt have "giveItems"
            - iron_sword: 1
            - bow: 1
            - tnt: 3
            - arrow: 32
            - leather_helm: 1
            - leather_chest: 1
            - leather_leggings: 1
            - leather_boot: 1
            - bread: 5
        enchants:
            - speed:1
    onDeath:
        options: [respawn,clearInventory]
    winner:
        options: [enchants, money=1,experience=300, health=20, hunger=20]
        enchants:
            - speed:2:900
            - resistance:2:900
            
tourney:
    enabled: true
    command: tourney